[package]
name = "opengraph"
version = "0.1.0"
authors = ["Hiroki Kumamoto <kumabook@live.jp>"]
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
serde        = "*"
serde_derive = "*"
serde_json   = "*"
html5ever    = "*"
